# Generated by Django 3.2.12 on 2022-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_per_hour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebody',
            name='number_of_field_types',
            field=models.JSONField(default={'field_type': str, 'field_type_amount': int, 'index_of_queries_to_db_list': int}),
        ),
    ]
