# Generated by Django 3.2.12 on 2022-02-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_per_hour', '0003_alter_tablebody_number_of_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebody',
            name='number_of_field_types',
            field=models.JSONField(default={'field_type': '', 'field_type_amount': 0, 'index_of_db_field_name_list': 0, 'index_of_queries_to_db_list': 0}),
        ),
    ]
