# Generated by Django 3.2.12 on 2022-02-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_apps', '0008_querytemplate'),
        ('summary_per_hour', '0005_alter_tablebody_number_of_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebody',
            name='number_of_field_types',
            field=models.JSONField(default=[{'db_field_name_pk': 0, 'field_type': '', 'field_type_amount': 0, 'index_of_queries_to_db_list': 0}]),
        ),
        migrations.AlterField(
            model_name='tablebodyfieldtype',
            name='query_to_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_web_apps.querytemplate'),
        ),
    ]
