# Generated by Django 3.2.12 on 2022-02-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary_per_hour', '0006_auto_20220215_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebodyfieldtype',
            old_name='query_to_db',
            new_name='query_templates',
        ),
    ]
