# Generated by Django 3.2.12 on 2022-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_per_hour', '0007_rename_query_to_db_tablebodyfieldtype_query_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebody',
            name='number_of_field_types',
            field=models.JSONField(default=[{'db_field_name_pk': 0, 'field_type': '', 'field_type_amount': 0, 'query_templates_index': 0}]),
        ),
    ]
