# Generated by Django 3.2.12 on 2022-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_per_hour', '0009_alter_tablebody_number_of_field_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebodyfieldtype',
            name='table_head_field_type',
        ),
        migrations.AddField(
            model_name='tablebodyfieldtype',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
