# Generated by Django 3.2.12 on 2022-02-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryToDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('query_to_db_list', models.JSONField()),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ip', models.CharField(default=None, max_length=150)),
                ('user', models.CharField(default=None, max_length=150)),
                ('password', models.CharField(default=None, max_length=150)),
                ('port', models.CharField(default=None, max_length=150)),
                ('driver', models.CharField(default=None, max_length=150)),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('db', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_web_apps.db')),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('db_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_web_apps.dbtable')),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='db',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_web_apps.server'),
        ),
    ]
