# Generated by Django 3.2.12 on 2022-02-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_apps', '0002_auto_20220213_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfield',
            name='name',
            field=models.JSONField(),
        ),
    ]
