# Generated by Django 3.2.12 on 2022-02-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_apps', '0004_alter_dbfield_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querytodb',
            old_name='query_to_db_list',
            new_name='queries_to_db_list',
        ),
    ]
