# Generated by Django 3.2.12 on 2022-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_apps', '0007_alter_dbfield_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('query_templates', models.JSONField(default=[])),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
    ]
