# Generated by Django 3.2.12 on 2022-02-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_apps', '0008_querytemplate'),
        ('summary_per_hour', '0006_auto_20220215_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryToDB',
        ),
    ]
