# Generated by Django 3.2.12 on 2022-02-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary_per_hour', '0010_auto_20220215_1839'),
        ('django_web_apps', '0009_delete_querytodb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryTemplate',
            new_name='Query',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='query_templates',
            new_name='templates',
        ),
    ]
